// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

#include "Response.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_Response_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Response_InitMultiplayerState_Response_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_Response_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Response_JoinState_Response_2eproto;
namespace response {
class Response_InitMultiplayerStateDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Response_InitMultiplayerState> _instance;
} _Response_InitMultiplayerState_default_instance_;
class Response_JoinStateDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Response_JoinState> _instance;
} _Response_JoinState_default_instance_;
class ResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Response> _instance;
} _Response_default_instance_;
}  // namespace response
static void InitDefaultsscc_info_Response_Response_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::response::_Response_default_instance_;
    new (ptr) ::response::Response();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::response::Response::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_Response_Response_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_Response_Response_2eproto}, {
      &scc_info_Response_InitMultiplayerState_Response_2eproto.base,
      &scc_info_Response_JoinState_Response_2eproto.base,}};

static void InitDefaultsscc_info_Response_InitMultiplayerState_Response_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::response::_Response_InitMultiplayerState_default_instance_;
    new (ptr) ::response::Response_InitMultiplayerState();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::response::Response_InitMultiplayerState::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Response_InitMultiplayerState_Response_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Response_InitMultiplayerState_Response_2eproto}, {}};

static void InitDefaultsscc_info_Response_JoinState_Response_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::response::_Response_JoinState_default_instance_;
    new (ptr) ::response::Response_JoinState();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::response::Response_JoinState::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Response_JoinState_Response_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Response_JoinState_Response_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Response_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Response_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Response_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Response_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::response::Response_InitMultiplayerState, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::response::Response_InitMultiplayerState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::response::Response_InitMultiplayerState, code_),
  0,
  PROTOBUF_FIELD_OFFSET(::response::Response_JoinState, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::response::Response_JoinState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::response::Response_JoinState, ok_),
  0,
  PROTOBUF_FIELD_OFFSET(::response::Response, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::response::Response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::response::Response, init_multiplayer_state_),
  PROTOBUF_FIELD_OFFSET(::response::Response, join_state_),
  0,
  1,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::response::Response_InitMultiplayerState)},
  { 7, 13, sizeof(::response::Response_JoinState)},
  { 14, 21, sizeof(::response::Response)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::response::_Response_InitMultiplayerState_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::response::_Response_JoinState_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::response::_Response_default_instance_),
};

const char descriptor_table_protodef_Response_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016Response.proto\022\010response\"\304\001\n\010Response\022"
  "G\n\026init_multiplayer_state\030\001 \001(\0132\'.respon"
  "se.Response.InitMultiplayerState\0220\n\njoin"
  "_state\030\002 \001(\0132\034.response.Response.JoinSta"
  "te\032$\n\024InitMultiplayerState\022\014\n\004code\030\001 \001(\t"
  "\032\027\n\tJoinState\022\n\n\002ok\030\001 \001(\010"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Response_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_Response_2eproto_sccs[3] = {
  &scc_info_Response_Response_2eproto.base,
  &scc_info_Response_InitMultiplayerState_Response_2eproto.base,
  &scc_info_Response_JoinState_Response_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Response_2eproto_once;
static bool descriptor_table_Response_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Response_2eproto = {
  &descriptor_table_Response_2eproto_initialized, descriptor_table_protodef_Response_2eproto, "Response.proto", 225,
  &descriptor_table_Response_2eproto_once, descriptor_table_Response_2eproto_sccs, descriptor_table_Response_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_Response_2eproto::offsets,
  file_level_metadata_Response_2eproto, 3, file_level_enum_descriptors_Response_2eproto, file_level_service_descriptors_Response_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_Response_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_Response_2eproto), true);
namespace response {

// ===================================================================

void Response_InitMultiplayerState::InitAsDefaultInstance() {
}
class Response_InitMultiplayerState::_Internal {
 public:
  using HasBits = decltype(std::declval<Response_InitMultiplayerState>()._has_bits_);
  static void set_has_code(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

Response_InitMultiplayerState::Response_InitMultiplayerState()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:response.Response.InitMultiplayerState)
}
Response_InitMultiplayerState::Response_InitMultiplayerState(const Response_InitMultiplayerState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  code_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_code()) {
    code_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.code_);
  }
  // @@protoc_insertion_point(copy_constructor:response.Response.InitMultiplayerState)
}

void Response_InitMultiplayerState::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Response_InitMultiplayerState_Response_2eproto.base);
  code_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

Response_InitMultiplayerState::~Response_InitMultiplayerState() {
  // @@protoc_insertion_point(destructor:response.Response.InitMultiplayerState)
  SharedDtor();
}

void Response_InitMultiplayerState::SharedDtor() {
  code_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Response_InitMultiplayerState::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Response_InitMultiplayerState& Response_InitMultiplayerState::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Response_InitMultiplayerState_Response_2eproto.base);
  return *internal_default_instance();
}


void Response_InitMultiplayerState::Clear() {
// @@protoc_insertion_point(message_clear_start:response.Response.InitMultiplayerState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    code_.ClearNonDefaultToEmptyNoArena();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* Response_InitMultiplayerState::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional string code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_code();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "response.Response.InitMultiplayerState.code");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Response_InitMultiplayerState::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:response.Response.InitMultiplayerState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string code = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_code().data(), static_cast<int>(this->_internal_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "response.Response.InitMultiplayerState.code");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:response.Response.InitMultiplayerState)
  return target;
}

size_t Response_InitMultiplayerState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:response.Response.InitMultiplayerState)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string code = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_code());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Response_InitMultiplayerState::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:response.Response.InitMultiplayerState)
  GOOGLE_DCHECK_NE(&from, this);
  const Response_InitMultiplayerState* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Response_InitMultiplayerState>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:response.Response.InitMultiplayerState)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:response.Response.InitMultiplayerState)
    MergeFrom(*source);
  }
}

void Response_InitMultiplayerState::MergeFrom(const Response_InitMultiplayerState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:response.Response.InitMultiplayerState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_code()) {
    _has_bits_[0] |= 0x00000001u;
    code_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.code_);
  }
}

void Response_InitMultiplayerState::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:response.Response.InitMultiplayerState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Response_InitMultiplayerState::CopyFrom(const Response_InitMultiplayerState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:response.Response.InitMultiplayerState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Response_InitMultiplayerState::IsInitialized() const {
  return true;
}

void Response_InitMultiplayerState::InternalSwap(Response_InitMultiplayerState* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  code_.Swap(&other->code_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata Response_InitMultiplayerState::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Response_JoinState::InitAsDefaultInstance() {
}
class Response_JoinState::_Internal {
 public:
  using HasBits = decltype(std::declval<Response_JoinState>()._has_bits_);
  static void set_has_ok(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

Response_JoinState::Response_JoinState()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:response.Response.JoinState)
}
Response_JoinState::Response_JoinState(const Response_JoinState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ok_ = from.ok_;
  // @@protoc_insertion_point(copy_constructor:response.Response.JoinState)
}

void Response_JoinState::SharedCtor() {
  ok_ = false;
}

Response_JoinState::~Response_JoinState() {
  // @@protoc_insertion_point(destructor:response.Response.JoinState)
  SharedDtor();
}

void Response_JoinState::SharedDtor() {
}

void Response_JoinState::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Response_JoinState& Response_JoinState::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Response_JoinState_Response_2eproto.base);
  return *internal_default_instance();
}


void Response_JoinState::Clear() {
// @@protoc_insertion_point(message_clear_start:response.Response.JoinState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ok_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* Response_JoinState::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional bool ok = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_ok(&has_bits);
          ok_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Response_JoinState::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:response.Response.JoinState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool ok = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_ok(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:response.Response.JoinState)
  return target;
}

size_t Response_JoinState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:response.Response.JoinState)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional bool ok = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Response_JoinState::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:response.Response.JoinState)
  GOOGLE_DCHECK_NE(&from, this);
  const Response_JoinState* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Response_JoinState>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:response.Response.JoinState)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:response.Response.JoinState)
    MergeFrom(*source);
  }
}

void Response_JoinState::MergeFrom(const Response_JoinState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:response.Response.JoinState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_ok()) {
    _internal_set_ok(from._internal_ok());
  }
}

void Response_JoinState::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:response.Response.JoinState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Response_JoinState::CopyFrom(const Response_JoinState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:response.Response.JoinState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Response_JoinState::IsInitialized() const {
  return true;
}

void Response_JoinState::InternalSwap(Response_JoinState* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(ok_, other->ok_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Response_JoinState::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Response::InitAsDefaultInstance() {
  ::response::_Response_default_instance_._instance.get_mutable()->init_multiplayer_state_ = const_cast< ::response::Response_InitMultiplayerState*>(
      ::response::Response_InitMultiplayerState::internal_default_instance());
  ::response::_Response_default_instance_._instance.get_mutable()->join_state_ = const_cast< ::response::Response_JoinState*>(
      ::response::Response_JoinState::internal_default_instance());
}
class Response::_Internal {
 public:
  using HasBits = decltype(std::declval<Response>()._has_bits_);
  static const ::response::Response_InitMultiplayerState& init_multiplayer_state(const Response* msg);
  static void set_has_init_multiplayer_state(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::response::Response_JoinState& join_state(const Response* msg);
  static void set_has_join_state(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::response::Response_InitMultiplayerState&
Response::_Internal::init_multiplayer_state(const Response* msg) {
  return *msg->init_multiplayer_state_;
}
const ::response::Response_JoinState&
Response::_Internal::join_state(const Response* msg) {
  return *msg->join_state_;
}
Response::Response()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:response.Response)
}
Response::Response(const Response& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_init_multiplayer_state()) {
    init_multiplayer_state_ = new ::response::Response_InitMultiplayerState(*from.init_multiplayer_state_);
  } else {
    init_multiplayer_state_ = nullptr;
  }
  if (from._internal_has_join_state()) {
    join_state_ = new ::response::Response_JoinState(*from.join_state_);
  } else {
    join_state_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:response.Response)
}

void Response::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Response_Response_2eproto.base);
  ::memset(&init_multiplayer_state_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&join_state_) -
      reinterpret_cast<char*>(&init_multiplayer_state_)) + sizeof(join_state_));
}

Response::~Response() {
  // @@protoc_insertion_point(destructor:response.Response)
  SharedDtor();
}

void Response::SharedDtor() {
  if (this != internal_default_instance()) delete init_multiplayer_state_;
  if (this != internal_default_instance()) delete join_state_;
}

void Response::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Response& Response::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Response_Response_2eproto.base);
  return *internal_default_instance();
}


void Response::Clear() {
// @@protoc_insertion_point(message_clear_start:response.Response)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(init_multiplayer_state_ != nullptr);
      init_multiplayer_state_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(join_state_ != nullptr);
      join_state_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* Response::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional .response.Response.InitMultiplayerState init_multiplayer_state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_init_multiplayer_state(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .response.Response.JoinState join_state = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_join_state(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Response::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:response.Response)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .response.Response.InitMultiplayerState init_multiplayer_state = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::init_multiplayer_state(this), target, stream);
  }

  // optional .response.Response.JoinState join_state = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::join_state(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:response.Response)
  return target;
}

size_t Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:response.Response)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional .response.Response.InitMultiplayerState init_multiplayer_state = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *init_multiplayer_state_);
    }

    // optional .response.Response.JoinState join_state = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *join_state_);
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Response::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:response.Response)
  GOOGLE_DCHECK_NE(&from, this);
  const Response* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Response>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:response.Response)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:response.Response)
    MergeFrom(*source);
  }
}

void Response::MergeFrom(const Response& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:response.Response)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_init_multiplayer_state()->::response::Response_InitMultiplayerState::MergeFrom(from._internal_init_multiplayer_state());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_join_state()->::response::Response_JoinState::MergeFrom(from._internal_join_state());
    }
  }
}

void Response::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:response.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Response::CopyFrom(const Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:response.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Response::IsInitialized() const {
  return true;
}

void Response::InternalSwap(Response* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(init_multiplayer_state_, other->init_multiplayer_state_);
  swap(join_state_, other->join_state_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Response::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace response
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::response::Response_InitMultiplayerState* Arena::CreateMaybeMessage< ::response::Response_InitMultiplayerState >(Arena* arena) {
  return Arena::CreateInternal< ::response::Response_InitMultiplayerState >(arena);
}
template<> PROTOBUF_NOINLINE ::response::Response_JoinState* Arena::CreateMaybeMessage< ::response::Response_JoinState >(Arena* arena) {
  return Arena::CreateInternal< ::response::Response_JoinState >(arena);
}
template<> PROTOBUF_NOINLINE ::response::Response* Arena::CreateMaybeMessage< ::response::Response >(Arena* arena) {
  return Arena::CreateInternal< ::response::Response >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
