// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Response_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Response_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Response_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Response_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Response_2eproto;
namespace response {
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class Response_InitMultiplayerState;
class Response_InitMultiplayerStateDefaultTypeInternal;
extern Response_InitMultiplayerStateDefaultTypeInternal _Response_InitMultiplayerState_default_instance_;
class Response_JoinState;
class Response_JoinStateDefaultTypeInternal;
extern Response_JoinStateDefaultTypeInternal _Response_JoinState_default_instance_;
}  // namespace response
PROTOBUF_NAMESPACE_OPEN
template<> ::response::Response* Arena::CreateMaybeMessage<::response::Response>(Arena*);
template<> ::response::Response_InitMultiplayerState* Arena::CreateMaybeMessage<::response::Response_InitMultiplayerState>(Arena*);
template<> ::response::Response_JoinState* Arena::CreateMaybeMessage<::response::Response_JoinState>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace response {

// ===================================================================

class Response_InitMultiplayerState :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:response.Response.InitMultiplayerState) */ {
 public:
  Response_InitMultiplayerState();
  virtual ~Response_InitMultiplayerState();

  Response_InitMultiplayerState(const Response_InitMultiplayerState& from);
  Response_InitMultiplayerState(Response_InitMultiplayerState&& from) noexcept
    : Response_InitMultiplayerState() {
    *this = ::std::move(from);
  }

  inline Response_InitMultiplayerState& operator=(const Response_InitMultiplayerState& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response_InitMultiplayerState& operator=(Response_InitMultiplayerState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Response_InitMultiplayerState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response_InitMultiplayerState* internal_default_instance() {
    return reinterpret_cast<const Response_InitMultiplayerState*>(
               &_Response_InitMultiplayerState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Response_InitMultiplayerState& a, Response_InitMultiplayerState& b) {
    a.Swap(&b);
  }
  inline void Swap(Response_InitMultiplayerState* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Response_InitMultiplayerState* New() const final {
    return CreateMaybeMessage<Response_InitMultiplayerState>(nullptr);
  }

  Response_InitMultiplayerState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Response_InitMultiplayerState>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Response_InitMultiplayerState& from);
  void MergeFrom(const Response_InitMultiplayerState& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response_InitMultiplayerState* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "response.Response.InitMultiplayerState";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Response_2eproto);
    return ::descriptor_table_Response_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCodeFieldNumber = 1,
  };
  // optional string code = 1;
  bool has_code() const;
  private:
  bool _internal_has_code() const;
  public:
  void clear_code();
  const std::string& code() const;
  void set_code(const std::string& value);
  void set_code(std::string&& value);
  void set_code(const char* value);
  void set_code(const char* value, size_t size);
  std::string* mutable_code();
  std::string* release_code();
  void set_allocated_code(std::string* code);
  private:
  const std::string& _internal_code() const;
  void _internal_set_code(const std::string& value);
  std::string* _internal_mutable_code();
  public:

  // @@protoc_insertion_point(class_scope:response.Response.InitMultiplayerState)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr code_;
  friend struct ::TableStruct_Response_2eproto;
};
// -------------------------------------------------------------------

class Response_JoinState :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:response.Response.JoinState) */ {
 public:
  Response_JoinState();
  virtual ~Response_JoinState();

  Response_JoinState(const Response_JoinState& from);
  Response_JoinState(Response_JoinState&& from) noexcept
    : Response_JoinState() {
    *this = ::std::move(from);
  }

  inline Response_JoinState& operator=(const Response_JoinState& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response_JoinState& operator=(Response_JoinState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Response_JoinState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response_JoinState* internal_default_instance() {
    return reinterpret_cast<const Response_JoinState*>(
               &_Response_JoinState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Response_JoinState& a, Response_JoinState& b) {
    a.Swap(&b);
  }
  inline void Swap(Response_JoinState* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Response_JoinState* New() const final {
    return CreateMaybeMessage<Response_JoinState>(nullptr);
  }

  Response_JoinState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Response_JoinState>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Response_JoinState& from);
  void MergeFrom(const Response_JoinState& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response_JoinState* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "response.Response.JoinState";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Response_2eproto);
    return ::descriptor_table_Response_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOkFieldNumber = 1,
  };
  // optional bool ok = 1;
  bool has_ok() const;
  private:
  bool _internal_has_ok() const;
  public:
  void clear_ok();
  bool ok() const;
  void set_ok(bool value);
  private:
  bool _internal_ok() const;
  void _internal_set_ok(bool value);
  public:

  // @@protoc_insertion_point(class_scope:response.Response.JoinState)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  bool ok_;
  friend struct ::TableStruct_Response_2eproto;
};
// -------------------------------------------------------------------

class Response :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:response.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const final {
    return CreateMaybeMessage<Response>(nullptr);
  }

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "response.Response";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Response_2eproto);
    return ::descriptor_table_Response_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Response_InitMultiplayerState InitMultiplayerState;
  typedef Response_JoinState JoinState;

  // accessors -------------------------------------------------------

  enum : int {
    kInitMultiplayerStateFieldNumber = 1,
    kJoinStateFieldNumber = 2,
  };
  // optional .response.Response.InitMultiplayerState init_multiplayer_state = 1;
  bool has_init_multiplayer_state() const;
  private:
  bool _internal_has_init_multiplayer_state() const;
  public:
  void clear_init_multiplayer_state();
  const ::response::Response_InitMultiplayerState& init_multiplayer_state() const;
  ::response::Response_InitMultiplayerState* release_init_multiplayer_state();
  ::response::Response_InitMultiplayerState* mutable_init_multiplayer_state();
  void set_allocated_init_multiplayer_state(::response::Response_InitMultiplayerState* init_multiplayer_state);
  private:
  const ::response::Response_InitMultiplayerState& _internal_init_multiplayer_state() const;
  ::response::Response_InitMultiplayerState* _internal_mutable_init_multiplayer_state();
  public:

  // optional .response.Response.JoinState join_state = 2;
  bool has_join_state() const;
  private:
  bool _internal_has_join_state() const;
  public:
  void clear_join_state();
  const ::response::Response_JoinState& join_state() const;
  ::response::Response_JoinState* release_join_state();
  ::response::Response_JoinState* mutable_join_state();
  void set_allocated_join_state(::response::Response_JoinState* join_state);
  private:
  const ::response::Response_JoinState& _internal_join_state() const;
  ::response::Response_JoinState* _internal_mutable_join_state();
  public:

  // @@protoc_insertion_point(class_scope:response.Response)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::response::Response_InitMultiplayerState* init_multiplayer_state_;
  ::response::Response_JoinState* join_state_;
  friend struct ::TableStruct_Response_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Response_InitMultiplayerState

// optional string code = 1;
inline bool Response_InitMultiplayerState::_internal_has_code() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Response_InitMultiplayerState::has_code() const {
  return _internal_has_code();
}
inline void Response_InitMultiplayerState::clear_code() {
  code_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Response_InitMultiplayerState::code() const {
  // @@protoc_insertion_point(field_get:response.Response.InitMultiplayerState.code)
  return _internal_code();
}
inline void Response_InitMultiplayerState::set_code(const std::string& value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:response.Response.InitMultiplayerState.code)
}
inline std::string* Response_InitMultiplayerState::mutable_code() {
  // @@protoc_insertion_point(field_mutable:response.Response.InitMultiplayerState.code)
  return _internal_mutable_code();
}
inline const std::string& Response_InitMultiplayerState::_internal_code() const {
  return code_.GetNoArena();
}
inline void Response_InitMultiplayerState::_internal_set_code(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  code_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Response_InitMultiplayerState::set_code(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  code_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:response.Response.InitMultiplayerState.code)
}
inline void Response_InitMultiplayerState::set_code(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  code_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:response.Response.InitMultiplayerState.code)
}
inline void Response_InitMultiplayerState::set_code(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  code_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:response.Response.InitMultiplayerState.code)
}
inline std::string* Response_InitMultiplayerState::_internal_mutable_code() {
  _has_bits_[0] |= 0x00000001u;
  return code_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Response_InitMultiplayerState::release_code() {
  // @@protoc_insertion_point(field_release:response.Response.InitMultiplayerState.code)
  if (!_internal_has_code()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return code_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Response_InitMultiplayerState::set_allocated_code(std::string* code) {
  if (code != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  code_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), code);
  // @@protoc_insertion_point(field_set_allocated:response.Response.InitMultiplayerState.code)
}

// -------------------------------------------------------------------

// Response_JoinState

// optional bool ok = 1;
inline bool Response_JoinState::_internal_has_ok() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Response_JoinState::has_ok() const {
  return _internal_has_ok();
}
inline void Response_JoinState::clear_ok() {
  ok_ = false;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool Response_JoinState::_internal_ok() const {
  return ok_;
}
inline bool Response_JoinState::ok() const {
  // @@protoc_insertion_point(field_get:response.Response.JoinState.ok)
  return _internal_ok();
}
inline void Response_JoinState::_internal_set_ok(bool value) {
  _has_bits_[0] |= 0x00000001u;
  ok_ = value;
}
inline void Response_JoinState::set_ok(bool value) {
  _internal_set_ok(value);
  // @@protoc_insertion_point(field_set:response.Response.JoinState.ok)
}

// -------------------------------------------------------------------

// Response

// optional .response.Response.InitMultiplayerState init_multiplayer_state = 1;
inline bool Response::_internal_has_init_multiplayer_state() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || init_multiplayer_state_ != nullptr);
  return value;
}
inline bool Response::has_init_multiplayer_state() const {
  return _internal_has_init_multiplayer_state();
}
inline void Response::clear_init_multiplayer_state() {
  if (init_multiplayer_state_ != nullptr) init_multiplayer_state_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::response::Response_InitMultiplayerState& Response::_internal_init_multiplayer_state() const {
  const ::response::Response_InitMultiplayerState* p = init_multiplayer_state_;
  return p != nullptr ? *p : *reinterpret_cast<const ::response::Response_InitMultiplayerState*>(
      &::response::_Response_InitMultiplayerState_default_instance_);
}
inline const ::response::Response_InitMultiplayerState& Response::init_multiplayer_state() const {
  // @@protoc_insertion_point(field_get:response.Response.init_multiplayer_state)
  return _internal_init_multiplayer_state();
}
inline ::response::Response_InitMultiplayerState* Response::release_init_multiplayer_state() {
  // @@protoc_insertion_point(field_release:response.Response.init_multiplayer_state)
  _has_bits_[0] &= ~0x00000001u;
  ::response::Response_InitMultiplayerState* temp = init_multiplayer_state_;
  init_multiplayer_state_ = nullptr;
  return temp;
}
inline ::response::Response_InitMultiplayerState* Response::_internal_mutable_init_multiplayer_state() {
  _has_bits_[0] |= 0x00000001u;
  if (init_multiplayer_state_ == nullptr) {
    auto* p = CreateMaybeMessage<::response::Response_InitMultiplayerState>(GetArenaNoVirtual());
    init_multiplayer_state_ = p;
  }
  return init_multiplayer_state_;
}
inline ::response::Response_InitMultiplayerState* Response::mutable_init_multiplayer_state() {
  // @@protoc_insertion_point(field_mutable:response.Response.init_multiplayer_state)
  return _internal_mutable_init_multiplayer_state();
}
inline void Response::set_allocated_init_multiplayer_state(::response::Response_InitMultiplayerState* init_multiplayer_state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete init_multiplayer_state_;
  }
  if (init_multiplayer_state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      init_multiplayer_state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, init_multiplayer_state, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  init_multiplayer_state_ = init_multiplayer_state;
  // @@protoc_insertion_point(field_set_allocated:response.Response.init_multiplayer_state)
}

// optional .response.Response.JoinState join_state = 2;
inline bool Response::_internal_has_join_state() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || join_state_ != nullptr);
  return value;
}
inline bool Response::has_join_state() const {
  return _internal_has_join_state();
}
inline void Response::clear_join_state() {
  if (join_state_ != nullptr) join_state_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::response::Response_JoinState& Response::_internal_join_state() const {
  const ::response::Response_JoinState* p = join_state_;
  return p != nullptr ? *p : *reinterpret_cast<const ::response::Response_JoinState*>(
      &::response::_Response_JoinState_default_instance_);
}
inline const ::response::Response_JoinState& Response::join_state() const {
  // @@protoc_insertion_point(field_get:response.Response.join_state)
  return _internal_join_state();
}
inline ::response::Response_JoinState* Response::release_join_state() {
  // @@protoc_insertion_point(field_release:response.Response.join_state)
  _has_bits_[0] &= ~0x00000002u;
  ::response::Response_JoinState* temp = join_state_;
  join_state_ = nullptr;
  return temp;
}
inline ::response::Response_JoinState* Response::_internal_mutable_join_state() {
  _has_bits_[0] |= 0x00000002u;
  if (join_state_ == nullptr) {
    auto* p = CreateMaybeMessage<::response::Response_JoinState>(GetArenaNoVirtual());
    join_state_ = p;
  }
  return join_state_;
}
inline ::response::Response_JoinState* Response::mutable_join_state() {
  // @@protoc_insertion_point(field_mutable:response.Response.join_state)
  return _internal_mutable_join_state();
}
inline void Response::set_allocated_join_state(::response::Response_JoinState* join_state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete join_state_;
  }
  if (join_state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      join_state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, join_state, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  join_state_ = join_state;
  // @@protoc_insertion_point(field_set_allocated:response.Response.join_state)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace response

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Response_2eproto
